name: Build and Run Java Program

on:
  push:
    branches:
      - main  # O workflow é acionado quando há um push para a branch principal
  pull_request:
    branches:
      - main  # O workflow também é acionado para pull requests na branch principal

jobs:
  build:
    runs-on: ubuntu-latest  # Usa a máquina Ubuntu para executar os comandos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Faz checkout do código do repositório

      - name: Set up Java
        uses: actions/setup-java@v2  # Configura o Java
        with:
          java-version: '17'  # Usando Java 17
          distribution: 'temurin'  # Usando a distribuição Temurin do OpenJDK

      - name: Install Gradle
        run: |
          # Baixa e instala o Gradle
          wget https://services.gradle.org/distributions/gradle-7.5.1-bin.zip -O gradle.zip
          unzip gradle.zip -d gradle
          export PATH=$PATH:$(pwd)/gradle/gradle-7.5.1/bin  # Adiciona o Gradle ao PATH

      - name: Generate Gradle Wrapper
        run: |
          # Cria um wrapper Gradle temporário se não existir
          echo "Creating Gradle wrapper"
          gradle wrapper  # Cria o wrapper do Gradle

      - name: Install Robocode (using robocode directory)
        run: |
          cd robocode  # Acessa a pasta 'robocode'
          chmod +x gradlew  # Dá permissão de execução ao script gradlew
          ./gradlew build  # Compila o código do Robocode
          export ROBODECODE_HOME=$(pwd)  # Define a variável de ambiente para o Robocode

      - name: Compile Java program
        run: javac DanielaRobot.java  # Compila o arquivo .java

      - name: Run Java program
        run: java DanielaRobot  # Executa o código Java compilado

        run: java DanielaRobot  # Executa o código Java compilado
