name: Caller Workflow

on:
  push:
    branches:
      - main  # O workflow é acionado quando há um push para a branch principal
  pull_request:
    branches:
      - main  # O workflow também é acionado para pull requests na branch principal

jobs:
  call-reusable-workflow:
    # Define o job que chama o workflow reutilizável
    uses: ./.github/workflows/ci.yml  # Caminho correto para o workflow reutilizável

    with:
      message: "Teste Realizado com sucesso"  # Passa a mensagem para o workflow reutilizável
